// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Logger {
        public static readonly string Name = "logger";

        // TABLES
        public static readonly QualifiedTableName LogConfig = "logger.LogConfig";
        public static readonly QualifiedTableName LogEntries = "logger.LogEntries";
        public static readonly QualifiedTableName LogEntryAttributes = "logger.LogEntryAttributes";
        public static readonly QualifiedTableName LogLevelCodes = "logger.LogLevelCodes";

        // VIEWS
        public static readonly QualifiedViewName LogEntryDeltaView = "logger.LogEntryDeltaView";
        public static readonly QualifiedViewName LogLevelCodesView = "logger.LogLevelCodesView";

        // STORED PROCEDURES
        public static readonly SQLProc AddLogEntryAttribute = "logger.AddLogEntryAttribute";
        public static readonly SQLProc AddLogEntryAttributes = "logger.AddLogEntryAttributes";
        public static readonly SQLProc AddOrUpdateLogEntryAttribute = "logger.AddOrUpdateLogEntryAttribute";
        public static readonly SQLProc AddOrUpdateLogEntryAttributes = "logger.AddOrUpdateLogEntryAttributes";
        public static readonly SQLProc CreateLogParameters = "logger.CreateLogParameters";
        public static readonly SQLProc Log = "logger.Log";
        public static readonly SQLProc LogEz = "logger.LogEz";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
