// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Dm {
        public static readonly string Name = "dm";

        // VIEWS
        public static readonly QualifiedViewName DimCalendar = "dm.dim_Calendar";
        public static readonly QualifiedViewName DimChargeCodes = "dm.dim_ChargeCodes";
        public static readonly QualifiedViewName DimChargeCostCenters = "dm.dim_ChargeCostCenters";
        public static readonly QualifiedViewName DimChargesPatientTypes = "dm.dim_ChargesPatientTypes";
        public static readonly QualifiedViewName DimCodeTypes = "dm.dim_CodeTypes";
        public static readonly QualifiedViewName DimCompositeKeys = "dm.dim_CompositeKeys";
        public static readonly QualifiedViewName DimCptCodes = "dm.dim_CPTCodes";
        public static readonly QualifiedViewName DimDepartments = "dm.dim_Departments";
        public static readonly QualifiedViewName DimDischargeDispositions = "dm.dim_DischargeDispositions";
        public static readonly QualifiedViewName DimEmployees = "dm.dim_Employees";
        public static readonly QualifiedViewName DimExemptionTypes = "dm.dim_ExemptionTypes";
        public static readonly QualifiedViewName DimFacilities = "dm.dim_Facilities";
        public static readonly QualifiedViewName DimFunctionalGroups = "dm.dim_FunctionalGroups";
        public static readonly QualifiedViewName DimHospitalDepartment = "dm.dim_HospitalDepartment";
        public static readonly QualifiedViewName DimHospitalServices = "dm.dim_HospitalServices";
        public static readonly QualifiedViewName DimJobCategories = "dm.dim_JobCategories";
        public static readonly QualifiedViewName DimJobCodes = "dm.dim_JobCodes";
        public static readonly QualifiedViewName DimJobTypes = "dm.dim_JobTypes";
        public static readonly QualifiedViewName DimPatientEncounters = "dm.dim_PatientEncounters";
        public static readonly QualifiedViewName DimPatientSubtypes = "dm.dim_PatientSubtypes";
        public static readonly QualifiedViewName DimPatientTypePatientSubTypeDischargeDispositions = "dm.dim_PatientTypePatientSubTypeDischargeDispositions";
        public static readonly QualifiedViewName DimPatientTypes = "dm.dim_PatientTypes";
        public static readonly QualifiedViewName DimPatientTypeWithDischargeDispositions = "dm.dim_PatientTypeWithDischargeDispositions";
        public static readonly QualifiedViewName DimPatientTypeWithPatientSubtypes = "dm.dim_PatientTypeWithPatientSubtypes";
        public static readonly QualifiedViewName DimPayTypeCategories = "dm.dim_PayTypeCategories";
        public static readonly QualifiedViewName DimPeriodSegments = "dm.dim_PeriodSegments";
        public static readonly QualifiedViewName DimProductivityStd = "dm.dim_ProductivityStd";
        public static readonly QualifiedViewName DimRevenueCodes = "dm.dim_RevenueCodes";
        public static readonly QualifiedViewName DimServiceCalendarDate = "dm.dim_ServiceCalendarDate";
        public static readonly QualifiedViewName DimTransactionPostDate = "dm.dim_TransactionPostDate";
        public static readonly QualifiedViewName DimVariables = "dm.dim_Variables";
        public static readonly QualifiedViewName DimVolumeIndicator = "dm.dim_VolumeIndicator";
        public static readonly QualifiedViewName FactActivityDetail = "dm.fact_ActivityDetail";
        public static readonly QualifiedViewName FactActivityDetailDepartment = "dm.fact_ActivityDetail_Department";
        public static readonly QualifiedViewName FactActivityDetailFacility = "dm.fact_ActivityDetail_Facility";
        public static readonly QualifiedViewName FactActualProductivity = "dm.fact_ActualProductivity";
        public static readonly QualifiedViewName FactActualWorkedHours = "dm.fact_ActualWorkedHours";
        public static readonly QualifiedViewName FactActualWorkedHoursDepartment = "dm.fact_ActualWorkedHours_Department";
        public static readonly QualifiedViewName FactActualWorkedHoursFacility = "dm.fact_ActualWorkedHours_Facility";
        public static readonly QualifiedViewName FactBottomDepartmentRank = "dm.fact_BottomDepartmentRank";
        public static readonly QualifiedViewName FactCharges = "dm.fact_Charges";
        public static readonly QualifiedViewName FactEmployeeWorkedHours = "dm.fact_EmployeeWorkedHours";
        public static readonly QualifiedViewName FactEstimatedLaborCost = "dm.fact_EstimatedLaborCost";
        public static readonly QualifiedViewName FactEstimatedLaborCostDepartment = "dm.fact_EstimatedLaborCost_Department";
        public static readonly QualifiedViewName FactEstimatedLaborCostFacility = "dm.fact_EstimatedLaborCost_Facility";
        public static readonly QualifiedViewName FactOccupancyDetail = "dm.fact_OccupancyDetail";
        public static readonly QualifiedViewName FactOccupancyDetailDepartment = "dm.fact_OccupancyDetail_Department";
        public static readonly QualifiedViewName FactOccupancyDetailFacility = "dm.fact_OccupancyDetail_Facility";
        public static readonly QualifiedViewName FactOvertimeHours = "dm.fact_OvertimeHours";
        public static readonly QualifiedViewName FactOvertimeHoursDepartment = "dm.fact_OvertimeHours_Department";
        public static readonly QualifiedViewName FactOvertimeHoursFacility = "dm.fact_OvertimeHours_Facility";
        public static readonly QualifiedViewName FactProductivityPercent = "dm.fact_ProductivityPercent";
        public static readonly QualifiedViewName FactProductivityPercentDepartment = "dm.fact_ProductivityPercent_Department";
        public static readonly QualifiedViewName FactProductivityPercentFacility = "dm.fact_ProductivityPercent_Facility";
        public static readonly QualifiedViewName FactRequiredLaborCost = "dm.fact_RequiredLaborCost";
        public static readonly QualifiedViewName FactRequiredLaborCostDepartment = "dm.fact_RequiredLaborCost_Department";
        public static readonly QualifiedViewName FactRequiredLaborCostFacility = "dm.fact_RequiredLaborCost_Facility";
        public static readonly QualifiedViewName FactRequiredWorkedHours = "dm.fact_RequiredWorkedHours";
        public static readonly QualifiedViewName FactRequiredWorkedHoursDepartment = "dm.fact_RequiredWorkedHours_Department";
        public static readonly QualifiedViewName FactRequiredWorkedHoursFacility = "dm.fact_RequiredWorkedHours_Facility";
        public static readonly QualifiedViewName FactStandardProductivity = "dm.fact_StandardProductivity";
        public static readonly QualifiedViewName FactTopDepartmentRank = "dm.fact_TopDepartmentRank";
        public static readonly QualifiedViewName FactVolumeSummary = "dm.fact_VolumeSummary";
        public static readonly QualifiedViewName FactVolumeSummaryAdmissionsDepartment = "dm.fact_VolumeSummary_Admissions_Department";
        public static readonly QualifiedViewName FactVolumeSummaryAdmissionsFacility = "dm.fact_VolumeSummary_Admissions_Facility";
        public static readonly QualifiedViewName FactVolumeSummaryDischargesDepartment = "dm.fact_VolumeSummary_Discharges_Department";
        public static readonly QualifiedViewName FactVolumeSummaryDischargesFacility = "dm.fact_VolumeSummary_Discharges_Facility";
        public static readonly QualifiedViewName SectionAccess = "dm.SectionAccess";
        public static readonly QualifiedViewName UdcUserAttributes = "dm.UdcUserAttributes";
        public static readonly QualifiedViewName UdcUsers = "dm.UdcUsers";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
