// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class RawProc {
        public static readonly string Name = "rawProc";

        // TABLES
        public static readonly QualifiedTableName DisplayToCostCenterDept = "rawProc.DisplayToCostCenterDept";
        public static readonly QualifiedTableName DisplayToOperationalDept = "rawProc.DisplayToOperationalDept";

        // VIEWS
        public static readonly QualifiedViewName VDisplayToOperationalDept = "rawProc.vDisplayToOperationalDept";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
