// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Datascripts {
        public static readonly string Name = "datascripts";

        // STORED PROCEDURES
        public static readonly SQLProc ActivityIdentiferTypesPopulate = "datascripts.ActivityIdentiferTypesPopulate";
        public static readonly SQLProc IdentiferTypesPopulate = "datascripts.IdentiferTypesPopulate";
        public static readonly SQLProc StaticDataScriptRunner = "datascripts.StaticDataScriptRunner";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
