// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Sec {
        public static readonly string Name = "sec";

        // TABLES
        public static readonly QualifiedTableName ControlledObjects = "sec.ControlledObjects";
        public static readonly QualifiedTableName ControlledObjectsHistory = "sec.ControlledObjectsHistory";
        public static readonly QualifiedTableName Objects = "sec.Objects";
        public static readonly QualifiedTableName ObjectsHistory = "sec.ObjectsHistory";
        public static readonly QualifiedTableName Permissions = "sec.Permissions";
        public static readonly QualifiedTableName PermissionsHistory = "sec.PermissionsHistory";
        public static readonly QualifiedTableName RoleColumnRestrictions = "sec.RoleColumnRestrictions";
        public static readonly QualifiedTableName RoleColumnRestrictionsHistory = "sec.RoleColumnRestrictionsHistory";
        public static readonly QualifiedTableName Roles = "sec.Roles";
        public static readonly QualifiedTableName RolesHistory = "sec.RolesHistory";
        public static readonly QualifiedTableName UserRoleDepartments = "sec.UserRoleDepartments";
        public static readonly QualifiedTableName UserRoleDepartmentsHistory = "sec.UserRoleDepartmentsHistory";
        public static readonly QualifiedTableName UserRoles = "sec.UserRoles";
        public static readonly QualifiedTableName UserRolesHistory = "sec.UserRolesHistory";
        public static readonly QualifiedTableName Users = "sec.Users";
        public static readonly QualifiedTableName UsersHistory = "sec.UsersHistory";

        // VIEWS
        public static readonly QualifiedViewName CranewareUserAttr = "sec.CranewareUserAttr";
        public static readonly QualifiedViewName CranewareUsers = "sec.CranewareUsers";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
