// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Frontend {
        public static readonly string Name = "frontend";

        // TABLES
        public static readonly QualifiedTableName BookmarkedReports = "frontend.BookmarkedReports";
        public static readonly QualifiedTableName Bookmarks = "frontend.Bookmarks";
        public static readonly QualifiedTableName Modules = "frontend.Modules";
        public static readonly QualifiedTableName ModuleSections = "frontend.ModuleSections";
        public static readonly QualifiedTableName MonthSchedules = "frontend.MonthSchedules";
        public static readonly QualifiedTableName ReportConfigurations = "frontend.ReportConfigurations";
        public static readonly QualifiedTableName Reports = "frontend.Reports";
        public static readonly QualifiedTableName ReportSections = "frontend.ReportSections";
        public static readonly QualifiedTableName ReportSubscriptions = "frontend.ReportSubscriptions";
        public static readonly QualifiedTableName ReportTransmissions = "frontend.ReportTransmissions";
        public static readonly QualifiedTableName ReportTransmissionTypes = "frontend.ReportTransmissionTypes";
        public static readonly QualifiedTableName SchedulePeriods = "frontend.SchedulePeriods";
        public static readonly QualifiedTableName Schedules = "frontend.Schedules";
        public static readonly QualifiedTableName Subscribers = "frontend.Subscribers";
        public static readonly QualifiedTableName Subscriptions = "frontend.Subscriptions";
        public static readonly QualifiedTableName Visuals = "frontend.Visuals";
        public static readonly QualifiedTableName WeekSchedules = "frontend.WeekSchedules";

        // VIEWS
        public static readonly QualifiedViewName GetVisualisations = "frontend.GetVisualisations";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
