// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Zdatascripts {
        public static readonly string Name = "zdatascripts";

        // STORED PROCEDURES
        public static readonly SQLProc LoggerSetupDefaults = "zdatascripts.Logger_SetupDefaults";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
