// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Dbo {
        public static readonly string Name = "dbo";

        // TABLES
        public static readonly QualifiedTableName RefactorLog = "dbo.__RefactorLog";
        public static readonly QualifiedTableName ActivityIdentifierTypes = "dbo.ActivityIdentifierTypes";
        public static readonly QualifiedTableName AggregationTypes = "dbo.AggregationTypes";
        public static readonly QualifiedTableName CalendarDates = "dbo.CalendarDates";
        public static readonly QualifiedTableName CodeTypes = "dbo.CodeTypes";
        public static readonly QualifiedTableName CustomerTimeZones = "dbo.CustomerTimeZones";
        public static readonly QualifiedTableName DatabaseLogs = "dbo.DatabaseLogs";
        public static readonly QualifiedTableName DepartmentConfiguredValues = "dbo.DepartmentConfiguredValues";
        public static readonly QualifiedTableName DischargeDispositions = "dbo.DischargeDispositions";
        public static readonly QualifiedTableName EventTypes = "dbo.EventTypes";
        public static readonly QualifiedTableName ExemptionTypes = "dbo.ExemptionTypes";
        public static readonly QualifiedTableName FunctionalGroups = "dbo.FunctionalGroups";
        public static readonly QualifiedTableName HospitalServices = "dbo.HospitalServices";
        public static readonly QualifiedTableName JobCategories = "dbo.JobCategories";
        public static readonly QualifiedTableName JobTypes = "dbo.JobTypes";
        public static readonly QualifiedTableName PatientSubtypes = "dbo.PatientSubtypes";
        public static readonly QualifiedTableName PatientTypes = "dbo.PatientTypes";
        public static readonly QualifiedTableName PayTypeCategories = "dbo.PayTypeCategories";
        public static readonly QualifiedTableName Periods = "dbo.Periods";
        public static readonly QualifiedTableName PeriodSegments = "dbo.PeriodSegments";
        public static readonly QualifiedTableName SchedulePeriod = "dbo.SchedulePeriod";
        public static readonly QualifiedTableName VariableInputs = "dbo.VariableInputs";
        public static readonly QualifiedTableName Variables = "dbo.Variables";
        public static readonly QualifiedTableName VariablesDefaultScopes = "dbo.Variables_DefaultScopes";

        // VIEWS
        public static readonly QualifiedViewName VDatabaseLogs = "dbo.vDatabaseLogs";
        public static readonly QualifiedViewName VMinMaxDateTime = "dbo.vMinMaxDateTime";

        // STORED PROCEDURES
        public static readonly SQLProc GetTableStatisticsEx = "dbo.GetTableStatisticsEx";
        public static readonly SQLProc GuessDataTypes = "dbo.GuessDataTypes";
        public static readonly SQLProc NewSequentialId = "dbo.NewSequentialId";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
