// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class WIP {
        public static readonly string Name = "WIP";

        // TABLES
        public static readonly QualifiedTableName LoadEpicArpbTransactions = "WIP.LOAD_Epic_ARPB_TRANSACTIONS";
        public static readonly QualifiedTableName LoadEpicClarityAdt = "WIP.LOAD_Epic_CLARITY_ADT";
        public static readonly QualifiedTableName LoadEpicClarityDep = "WIP.LOAD_Epic_CLARITY_DEP";
        public static readonly QualifiedTableName LoadEpicClarityUcl = "WIP.LOAD_Epic_CLARITY_UCL";
        public static readonly QualifiedTableName LoadEpicHspAccount = "WIP.LOAD_Epic_HSP_ACCOUNT";
        public static readonly QualifiedTableName LoadEpicHspAcctCptCodes = "WIP.LOAD_Epic_HSP_ACCT_CPT_CODES";
        public static readonly QualifiedTableName LoadEpicHspTransactions = "WIP.LOAD_Epic_HSP_TRANSACTIONS";
        public static readonly QualifiedTableName LoadEpicPatEnc = "WIP.LOAD_Epic_PAT_ENC";
        public static readonly QualifiedTableName LoadEpicPatEncHsp = "WIP.LOAD_Epic_PAT_ENC_HSP";
        public static readonly QualifiedTableName LoadEpicZcAcctBaseclsHa = "WIP.LOAD_Epic_ZC_ACCT_BASECLS_HA";
        public static readonly QualifiedTableName LoadEpicZcAcctClassHa = "WIP.LOAD_Epic_ZC_ACCT_CLASS_HA";
        public static readonly QualifiedTableName LoadEpicZcDischDisp = "WIP.LOAD_Epic_ZC_DISCH_DISP";
        public static readonly QualifiedTableName LoadEpicZcEventSubtype = "WIP.LOAD_Epic_ZC_EVENT_SUBTYPE";
        public static readonly QualifiedTableName LoadEpicZcEventType = "WIP.LOAD_Epic_ZC_EVENT_TYPE";
        public static readonly QualifiedTableName LoadEpicZcMcAdmType = "WIP.LOAD_Epic_ZC_MC_ADM_TYPE";
        public static readonly QualifiedTableName ProcChargeProxyTimes = "WIP.PROC_ChargeProxyTimes";
        public static readonly QualifiedTableName ProcDepartmentConfiguredValueEntries = "WIP.PROC_DepartmentConfiguredValueEntries";
        public static readonly QualifiedTableName ProcDepartmentDetails = "WIP.PROC_DepartmentDetails";
        public static readonly QualifiedTableName ProcDisplayToCostCenterDept = "WIP.PROC_DisplayToCostCenterDept";
        public static readonly QualifiedTableName ProcDisplayToOperationalDept = "WIP.PROC_DisplayToOperationalDept";
        public static readonly QualifiedTableName ProcEmployeeRoster = "WIP.PROC_EmployeeRoster";
        public static readonly QualifiedTableName ProcEmployeeRosterOne = "WIP.PROC_EmployeeRosterOne";
        public static readonly QualifiedTableName ProcFacilityDetails = "WIP.PROC_FacilityDetails";
        public static readonly QualifiedTableName ProcTimeDetails = "WIP.PROC_TimeDetails";
        public static readonly QualifiedTableName SandboxTimeDetails = "WIP.SANDBOX_TimeDetails";
        public static readonly QualifiedTableName SandboxTimeDetailsDataTyped = "WIP.SANDBOX_TimeDetails_DataTyped";
        public static readonly QualifiedTableName StageChargeProxyTimes = "WIP.STAGE_ChargeProxyTimes";
        public static readonly QualifiedTableName StageCustomers = "WIP.STAGE_Customers";
        public static readonly QualifiedTableName StageDepartmentConfiguredValueEntries = "WIP.STAGE_DepartmentConfiguredValueEntries";
        public static readonly QualifiedTableName StageDepartmentDetails = "WIP.STAGE_DepartmentDetails";
        public static readonly QualifiedTableName StageDepartments = "WIP.STAGE_Departments";
        public static readonly QualifiedTableName StageDischargeDispositionMappings = "WIP.STAGE_DischargeDispositionMappings";
        public static readonly QualifiedTableName StageFacilities = "WIP.STAGE_Facilities";
        public static readonly QualifiedTableName StageFacilityDetails = "WIP.STAGE_FacilityDetails";
        public static readonly QualifiedTableName StageJobCodeMappings = "WIP.STAGE_JobCodeMappings";
        public static readonly QualifiedTableName StageUserDirectories = "WIP.STAGE_UserDirectories";
        public static readonly QualifiedTableName StageUserDirectoryMemberships = "WIP.STAGE_UserDirectoryMemberships";
        public static readonly QualifiedTableName StageUserRoleDepartments = "WIP.STAGE_UserRoleDepartments";
        public static readonly QualifiedTableName StageUserRoles = "WIP.STAGE_UserRoles";
        public static readonly QualifiedTableName StageUsers = "WIP.STAGE_Users";
        public static readonly QualifiedTableName TempMergeLaborEmployeeDetails = "WIP.TempMerge_laborEmployeeDetails";
        public static readonly QualifiedTableName TempMergeLaborEmployees = "WIP.TempMerge_laborEmployees";
        public static readonly QualifiedTableName TempMergeLaborTimesheetEntries = "WIP.TempMerge_laborTimesheetEntries";
        public static readonly QualifiedTableName TempMergeLaborTimesheetEntriesMissing = "WIP.TempMerge_laborTimesheetEntries_missing";
        public static readonly QualifiedTableName VariableScopes = "WIP.VariableScopes";
        public static readonly QualifiedTableName ZbakCalculatedVariables = "WIP.ZBAK_CalculatedVariables";
        public static readonly QualifiedTableName ZbakCalculatedVariables20230814 = "WIP.ZBAK_CalculatedVariables_20230814";
        public static readonly QualifiedTableName ZbakCalculatedVariables20231201 = "WIP.ZBAK_CalculatedVariables_20231201";
        public static readonly QualifiedTableName ZbakCalculatedVariables20231220 = "WIP.ZBAK_CalculatedVariables_20231220";
        public static readonly QualifiedTableName ZbakEmployeePayRates20230814 = "WIP.ZBAK_EmployeePayRates_20230814";
        public static readonly QualifiedTableName ZbakEpicPatEncHspDataTyped20240306 = "WIP.ZBAK_Epic_PAT_ENC_HSP_DataTyped_2024_03_06";

        // STORED PROCEDURES
        public static readonly SQLProc ProcDepartmentConfiguredValueEntriesMerge = "WIP.ProcDepartmentConfiguredValueEntries_Merge";
        public static readonly SQLProc ProcDepartmentDetailsMerge = "WIP.ProcDepartmentDetails_Merge";
        public static readonly SQLProc ProcDisplayToCostCenterDeptMerge = "WIP.ProcDisplayToCostCenterDept_Merge";
        public static readonly SQLProc ProcDisplayToOperationalDeptMerge = "WIP.ProcDisplayToOperationalDept_Merge";
        public static readonly SQLProc ProcFacilityDetailsMerge = "WIP.ProcFacilityDetails_Merge";
        public static readonly SQLProc TemplateEtlProcedure = "WIP.TemplateETLProcedure";
        public static readonly SQLProc TestProcIdSetCurrent = "WIP.TestProcId_SetCurrent";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
