// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Cal {
        public static readonly string Name = "cal";

        // TABLES
        public static readonly QualifiedTableName CalendarDays = "cal.CalendarDays";

        // STORED PROCEDURES
        public static readonly SQLProc GenerateCalendarDim = "cal.GenerateCalendarDim";
        public static readonly SQLProc PopulateCalendarDays = "cal.Populate_CalendarDays";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
