// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Cfg {
        public static readonly string Name = "cfg";

        // TABLES
        public static readonly QualifiedTableName ChargeProxyTimes = "cfg.ChargeProxyTimes";
        public static readonly QualifiedTableName ChargeProxyTimesHistory = "cfg.ChargeProxyTimesHistory";
        public static readonly QualifiedTableName Customers = "cfg.Customers";
        public static readonly QualifiedTableName CustomersHistory = "cfg.CustomersHistory";
        public static readonly QualifiedTableName DepartmentConfiguredValueEntries = "cfg.DepartmentConfiguredValueEntries";
        public static readonly QualifiedTableName DepartmentConfiguredValueEntriesHistory = "cfg.DepartmentConfiguredValueEntriesHistory";
        public static readonly QualifiedTableName DepartmentDetails = "cfg.DepartmentDetails";
        public static readonly QualifiedTableName DepartmentDetailsHistory = "cfg.DepartmentDetailsHistory";
        public static readonly QualifiedTableName Departments = "cfg.Departments";
        public static readonly QualifiedTableName DepartmentsHistory = "cfg.DepartmentsHistory";
        public static readonly QualifiedTableName DischargeDispositionMappings = "cfg.DischargeDispositionMappings";
        public static readonly QualifiedTableName DischargeDispositionMappingsHistory = "cfg.DischargeDispositionMappingsHistory";
        public static readonly QualifiedTableName Facilities = "cfg.Facilities";
        public static readonly QualifiedTableName FacilitiesHistory = "cfg.FacilitiesHistory";
        public static readonly QualifiedTableName FacilityDetails = "cfg.FacilityDetails";
        public static readonly QualifiedTableName FacilityDetailsHistory = "cfg.FacilityDetailsHistory";
        public static readonly QualifiedTableName FacilityOrdering = "cfg.FacilityOrdering";
        public static readonly QualifiedTableName JobCodeDetails = "cfg.JobCodeDetails";
        public static readonly QualifiedTableName JobCodeDetailsHistory = "cfg.JobCodeDetailsHistory";
        public static readonly QualifiedTableName JobCodeMappings = "cfg.JobCodeMappings";
        public static readonly QualifiedTableName JobCodeMappingsHistory = "cfg.JobCodeMappingsHistory";
        public static readonly QualifiedTableName JobCodes = "cfg.JobCodes";
        public static readonly QualifiedTableName JobCodesHistory = "cfg.JobCodesHistory";
        public static readonly QualifiedTableName PayTypeMappings = "cfg.PayTypeMappings";
        public static readonly QualifiedTableName PayTypesHistory = "cfg.PayTypesHistory";
        public static readonly QualifiedTableName VariableScopes = "cfg.VariableScopes";
        public static readonly QualifiedTableName VariableScopesHistory = "cfg.VariableScopesHistory";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
