// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class RawAltAlomere {
        public static readonly string Name = "rawAltAlomere";

        // TABLES
        public static readonly QualifiedTableName AdpTimeDetails = "rawAltAlomere.Adp_TimeDetails";
        public static readonly QualifiedTableName EmployeeRoster = "rawAltAlomere.EmployeeRoster";
        public static readonly QualifiedTableName TimeDetails = "rawAltAlomere.TimeDetails";
        public static readonly QualifiedTableName ZbakTimeDetails20231002 = "rawAltAlomere.ZBAK_TimeDetails_20231002";
        public static readonly QualifiedTableName ZwipEmployeeRoster = "rawAltAlomere.ZWIP_EmployeeRoster";
        public static readonly QualifiedTableName ZwipTimeDetails = "rawAltAlomere.ZWIP_TimeDetails";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
