// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Labor {
        public static readonly string Name = "labor";

        // TABLES
        public static readonly QualifiedTableName CalculatedVariables = "labor.CalculatedVariables";
        public static readonly QualifiedTableName ChargeCodes = "labor.ChargeCodes";
        public static readonly QualifiedTableName ChargeCostCenters = "labor.ChargeCostCenters";
        public static readonly QualifiedTableName Charges = "labor.Charges";
        public static readonly QualifiedTableName DateDepartmentDataMartIds = "labor.DateDepartmentDataMartIds";
        public static readonly QualifiedTableName DateDepartmentJobCategoryDataMartIds = "labor.DateDepartmentJobCategoryDataMartIds";
        public static readonly QualifiedTableName DateDepartmentJobCodeDataMartIds = "labor.DateDepartmentJobCodeDataMartIds";
        public static readonly QualifiedTableName Days = "labor.Days";
        public static readonly QualifiedTableName DaysHistory = "labor.DaysHistory";
        public static readonly QualifiedTableName DepartmentActivity = "labor.DepartmentActivity";
        public static readonly QualifiedTableName DepartmentJobCategoryDataMartIds = "labor.DepartmentJobCategoryDataMartIds";
        public static readonly QualifiedTableName EmployeeDetails = "labor.EmployeeDetails";
        public static readonly QualifiedTableName EmployeeDetailsHistory = "labor.EmployeeDetailsHistory";
        public static readonly QualifiedTableName EmployeePayRates = "labor.EmployeePayRates";
        public static readonly QualifiedTableName EmployeePayRatesHistory = "labor.EmployeePayRatesHistory";
        public static readonly QualifiedTableName Employees = "labor.Employees";
        public static readonly QualifiedTableName EmployeesHistory = "labor.EmployeesHistory";
        public static readonly QualifiedTableName IdentifierTypes = "labor.IdentifierTypes";
        public static readonly QualifiedTableName IdentifierTypesIi = "labor.IdentifierTypesII";
        public static readonly QualifiedTableName PartyIdentifiers = "labor.PartyIdentifiers";
        public static readonly QualifiedTableName PartyIdentifiersIi = "labor.PartyIdentifiersII";
        public static readonly QualifiedTableName PatientEncounterIdentifiers = "labor.PatientEncounterIdentifiers";
        public static readonly QualifiedTableName PatientEncounters = "labor.PatientEncounters";
        public static readonly QualifiedTableName ProductivityEvents = "labor.ProductivityEvents";
        public static readonly QualifiedTableName TimesheetEntries = "labor.TimesheetEntries";

        // VIEWS
        public static readonly QualifiedViewName VPartyIdentifiers = "labor.vPartyIdentifiers";
        public static readonly QualifiedViewName VPartyIdentifiersIi = "labor.vPartyIdentifiersII";

        // STORED PROCEDURES
        public static readonly SQLProc PopulateDataMartIds = "labor.PopulateDataMartIds";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
