// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class LaborProc {
        public static readonly string Name = "laborProc";

        // STORED PROCEDURES
        public static readonly SQLProc GetActiveEmployeeCount = "laborProc.GetActiveEmployeeCount";
        public static readonly SQLProc GetActiveEmployeeHourlyRates = "laborProc.GetActiveEmployeeHourlyRates";
        public static readonly SQLProc GetCalculatedValues = "laborProc.GetCalculatedValues";
        public static readonly SQLProc GetCharges = "laborProc.GetCharges";
        public static readonly SQLProc GetConstantValues = "laborProc.GetConstantValues";
        public static readonly SQLProc GetDepartmentActivity = "laborProc.GetDepartmentActivity";
        public static readonly SQLProc GetDepartments = "laborProc.GetDepartments";
        public static readonly SQLProc GetEmployeeEvents = "laborProc.GetEmployeeEvents";
        public static readonly SQLProc GetEvents = "laborProc.GetEvents";
        public static readonly SQLProc GetFacility = "laborProc.GetFacility";
        public static readonly SQLProc GetInputScopes = "laborProc.GetInputScopes";
        public static readonly SQLProc GetJobCodes = "laborProc.GetJobCodes";
        public static readonly SQLProc GetPatientEvents = "laborProc.GetPatientEvents";
        public static readonly SQLProc GetTimesheetEntries = "laborProc.GetTimesheetEntries";
        public static readonly SQLProc MergeCalculatedVariables = "laborProc.MergeCalculatedVariables";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
