// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Trisus {
        public static readonly string Name = "trisus";

        // TABLES
        public static readonly QualifiedTableName EmailTemplateIdentifiers = "trisus.EmailTemplateIdentifiers";
        public static readonly QualifiedTableName UserAttributes = "trisus.UserAttributes";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
