// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Ops {
        public static readonly string Name = "ops";

        // TABLES
        public static readonly QualifiedTableName DataLoadRecord = "ops.DataLoadRecord";
        public static readonly QualifiedTableName FileClassToTableMappings = "ops.FileClassToTableMappings";
        public static readonly QualifiedTableName FileConversionSpecs = "ops.FileConversionSpecs";
        public static readonly QualifiedTableName ProcessingDateRange = "ops.ProcessingDateRange";
        public static readonly QualifiedTableName RequiredFiles = "ops.RequiredFiles";

        // VIEWS
        public static readonly QualifiedViewName VRequiredFiles = "ops.vRequiredFiles";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
