// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class RawAltAlomereProc {
        public static readonly string Name = "rawAltAlomereProc";

        // TABLES
        public static readonly QualifiedTableName AdpTimeDetails = "rawAltAlomereProc.Adp_TimeDetails";
        public static readonly QualifiedTableName AdpTimeDetailsDataTyped = "rawAltAlomereProc.Adp_TimeDetails_DataTyped";
        public static readonly QualifiedTableName EmployeeRoster = "rawAltAlomereProc.EmployeeRoster";
        public static readonly QualifiedTableName EmployeeRosterDataTyped = "rawAltAlomereProc.EmployeeRoster_DataTyped";
        public static readonly QualifiedTableName TimeDetails = "rawAltAlomereProc.TimeDetails";
        public static readonly QualifiedTableName TimeDetailsDataTyped = "rawAltAlomereProc.TimeDetails_DataTyped";
        public static readonly QualifiedTableName ZbakTimeDetails20231002 = "rawAltAlomereProc.ZBAK_TimeDetails_20231002";

        // VIEWS
        public static readonly QualifiedViewName VCcDepartmentToOperational = "rawAltAlomereProc.vCCDepartmentToOperational";
        public static readonly QualifiedViewName VCostCenters = "rawAltAlomereProc.vCostCenters";
        public static readonly QualifiedViewName VDepartments = "rawAltAlomereProc.vDepartments";
        public static readonly QualifiedViewName VDepartmentUidToCcDepartmentId = "rawAltAlomereProc.vDepartmentUIDToCCDepartmentId";
        public static readonly QualifiedViewName VEmployeeRoster = "rawAltAlomereProc.VEmployeeRoster";
        public static readonly QualifiedViewName VEmployeeStatusDetail = "rawAltAlomereProc.vEmployeeStatusDetail";
        public static readonly QualifiedViewName VPatientEncountersOfInterest = "rawAltAlomereProc.vPatientEncountersOfInterest";

        // STORED PROCEDURES
        public static readonly SQLProc EmployeeRosterDataTyping = "rawAltAlomereProc.EmployeeRoster_DataTyping";
        public static readonly SQLProc EmployeeRosterSetCurrent = "rawAltAlomereProc.EmployeeRoster_SetCurrent";
        public static readonly SQLProc TimeDetailsDataTyping = "rawAltAlomereProc.TimeDetails_DataTyping";
        public static readonly SQLProc TimeDetailsSetCurrent = "rawAltAlomereProc.TimeDetails_SetCurrent";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
