// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Ref {
        public static readonly string Name = "ref";

        // TABLES
        public static readonly QualifiedTableName LCptCodes = "ref.L_CPT_CODES";
        public static readonly QualifiedTableName LRevCode = "ref.L_REV_CODE";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
