// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Sys {
        public static readonly string Name = "sys";

        // VIEWS
        public static readonly QualifiedViewName DatabaseFirewallRules = "sys.database_firewall_rules";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
