// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Product {
        public static readonly string Name = "product";

        // TABLES
        public static readonly QualifiedTableName Instances = "product.Instances";
        public static readonly QualifiedTableName Products = "product.Products";
        public static readonly QualifiedTableName UserDirectories = "product.UserDirectories";
        public static readonly QualifiedTableName UserDirectoryMemberships = "product.UserDirectoryMemberships";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
