// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Utils {
        public static readonly string Name = "utils";

        // VIEWS
        public static readonly QualifiedViewName InfoSchemaColumns = "utils.InfoSchema_Columns";
        public static readonly QualifiedViewName InfoSchemaTables = "utils.InfoSchema_Tables";
        public static readonly QualifiedViewName VSysTypeCategories = "utils.V_SysTypeCategories";

        // STORED PROCEDURES
        public static readonly SQLProc CreateSequentialIds = "utils.CreateSequentialIds";
        public static readonly SQLProc GenerateMergeStatement = "utils.GenerateMergeStatement";
        public static readonly SQLProc GenerateMergeStatementEx = "utils.GenerateMergeStatementEx";
        public static readonly SQLProc GenerateMergeStatementExUnique = "utils.GenerateMergeStatementExUnique";
        public static readonly SQLProc GetTableStatisticsEx = "utils.GetTableStatisticsEx";
        public static readonly SQLProc GuessDataTypes = "utils.GuessDataTypes";
        public static readonly SQLProc GuessDataTypesBasic = "utils.GuessDataTypesBasic";
        public static readonly SQLProc GuessDataTypesD2 = "utils.GuessDataTypesD2";
        public static readonly SQLProc MergerStatementGenerator = "utils.MergerStatementGenerator";
        public static readonly SQLProc SpMSforeachWorker = "utils.sp_MSforeach_worker";
        public static readonly SQLProc SpMSforeachtable = "utils.sp_MSforeachtable";
        public static readonly SQLProc Timer = "utils.Timer";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
