// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class RawEmrEpicClarityProc {
        public static readonly string Name = "rawEmrEpicClarityProc";

        // TABLES
        public static readonly QualifiedTableName EpicArpbTransactions = "rawEmrEpicClarityProc.Epic_ARPB_TRANSACTIONS";
        public static readonly QualifiedTableName EpicArpbTransactionsDataTyped = "rawEmrEpicClarityProc.Epic_ARPB_TRANSACTIONS_DataTyped";
        public static readonly QualifiedTableName EpicClarityAdt = "rawEmrEpicClarityProc.Epic_CLARITY_ADT";
        public static readonly QualifiedTableName EpicClarityAdtDataTyped = "rawEmrEpicClarityProc.Epic_CLARITY_ADT_DataTyped";
        public static readonly QualifiedTableName EpicClarityDep = "rawEmrEpicClarityProc.Epic_CLARITY_DEP";
        public static readonly QualifiedTableName EpicClarityDepDataTyped = "rawEmrEpicClarityProc.Epic_CLARITY_DEP_DataTyped";
        public static readonly QualifiedTableName EpicClarityTdlTran = "rawEmrEpicClarityProc.Epic_CLARITY_TDL_TRAN";
        public static readonly QualifiedTableName EpicClarityUcl = "rawEmrEpicClarityProc.Epic_CLARITY_UCL";
        public static readonly QualifiedTableName EpicClarityUclDataTyped = "rawEmrEpicClarityProc.Epic_CLARITY_UCL_DataTyped";
        public static readonly QualifiedTableName EpicHspAccount = "rawEmrEpicClarityProc.Epic_HSP_ACCOUNT";
        public static readonly QualifiedTableName EpicHspAccountDataTyped = "rawEmrEpicClarityProc.Epic_HSP_ACCOUNT_DataTyped";
        public static readonly QualifiedTableName EpicHspAcctCptCodes = "rawEmrEpicClarityProc.Epic_HSP_ACCT_CPT_CODES";
        public static readonly QualifiedTableName EpicHspAcctCptCodesDataTyped = "rawEmrEpicClarityProc.Epic_HSP_ACCT_CPT_CODES_DataTyped";
        public static readonly QualifiedTableName EpicHspTransactions = "rawEmrEpicClarityProc.Epic_HSP_TRANSACTIONS";
        public static readonly QualifiedTableName EpicHspTransactionsDataTyped = "rawEmrEpicClarityProc.Epic_HSP_TRANSACTIONS_DataTyped";
        public static readonly QualifiedTableName EpicPatEnc = "rawEmrEpicClarityProc.Epic_PAT_ENC";
        public static readonly QualifiedTableName EpicPatEncDataTyped = "rawEmrEpicClarityProc.Epic_PAT_ENC_DataTyped";
        public static readonly QualifiedTableName EpicPatEncHsp = "rawEmrEpicClarityProc.Epic_PAT_ENC_HSP";
        public static readonly QualifiedTableName EpicPatEncHspDataTyped = "rawEmrEpicClarityProc.Epic_PAT_ENC_HSP_DataTyped";
        public static readonly QualifiedTableName EpicZcAcctBaseclsHa = "rawEmrEpicClarityProc.Epic_ZC_ACCT_BASECLS_HA";
        public static readonly QualifiedTableName EpicZcAcctBaseclsHaDataTyped = "rawEmrEpicClarityProc.Epic_ZC_ACCT_BASECLS_HA_DataTyped";
        public static readonly QualifiedTableName EpicZcAcctClassHa = "rawEmrEpicClarityProc.Epic_ZC_ACCT_CLASS_HA";
        public static readonly QualifiedTableName EpicZcAcctClassHaDataTyped = "rawEmrEpicClarityProc.Epic_ZC_ACCT_CLASS_HA_DataTyped";
        public static readonly QualifiedTableName EpicZcDischDisp = "rawEmrEpicClarityProc.Epic_ZC_DISCH_DISP";
        public static readonly QualifiedTableName EpicZcDischDispDataTyped = "rawEmrEpicClarityProc.Epic_ZC_DISCH_DISP_DataTyped";
        public static readonly QualifiedTableName EpicZcEventSubtype = "rawEmrEpicClarityProc.Epic_ZC_EVENT_SUBTYPE";
        public static readonly QualifiedTableName EpicZcEventSubtypeDataTyped = "rawEmrEpicClarityProc.Epic_ZC_EVENT_SUBTYPE_DataTyped";
        public static readonly QualifiedTableName EpicZcEventType = "rawEmrEpicClarityProc.Epic_ZC_EVENT_TYPE";
        public static readonly QualifiedTableName EpicZcEventTypeDataTyped = "rawEmrEpicClarityProc.Epic_ZC_EVENT_TYPE_DataTyped";
        public static readonly QualifiedTableName EpicZcMcAdmType = "rawEmrEpicClarityProc.Epic_ZC_MC_ADM_TYPE";
        public static readonly QualifiedTableName EpicZcMcAdmTypeDataTyped = "rawEmrEpicClarityProc.Epic_ZC_MC_ADM_TYPE_DataTyped";

        // VIEWS
        public static readonly QualifiedViewName VDischDispCToDischargeDispositionId = "rawEmrEpicClarityProc.vDISCH_DISP_C_To_DischargeDispositionId";
        public static readonly QualifiedViewName VEpicClCostCntrOnly = "rawEmrEpicClarityProc.vEpic_CL_COST_CNTR_Only";
        public static readonly QualifiedViewName VEpicClarityAdt = "rawEmrEpicClarityProc.vEpic_CLARITY_ADT";
        public static readonly QualifiedViewName VEpicClarityDep = "rawEmrEpicClarityProc.vEpic_CLARITY_DEP";
        public static readonly QualifiedViewName VEpicPatEnc = "rawEmrEpicClarityProc.vEpic_PAT_ENC";
        public static readonly QualifiedViewName VEpicZcPatClass = "rawEmrEpicClarityProc.vEpic_ZC_PAT_CLASS";

        // STORED PROCEDURES
        public static readonly SQLProc AllProcessing = "rawEmrEpicClarityProc.AllProcessing";
        public static readonly SQLProc EpicArpbTransactionsDataTyping = "rawEmrEpicClarityProc.Epic_ARPB_TRANSACTIONS_DataTyping";
        public static readonly SQLProc EpicArpbTransactionsSetCurrent = "rawEmrEpicClarityProc.Epic_ARPB_TRANSACTIONS_SetCurrent";
        public static readonly SQLProc EpicClarityAdtDataTyping = "rawEmrEpicClarityProc.Epic_CLARITY_ADT_DataTyping";
        public static readonly SQLProc EpicClarityAdtSetCurrent = "rawEmrEpicClarityProc.Epic_CLARITY_ADT_SetCurrent";
        public static readonly SQLProc EpicClarityDepDataTyping = "rawEmrEpicClarityProc.Epic_CLARITY_DEP_DataTyping";
        public static readonly SQLProc EpicClarityDepSetCurrent = "rawEmrEpicClarityProc.Epic_CLARITY_DEP_SetCurrent";
        public static readonly SQLProc EpicClarityUclDataTyping = "rawEmrEpicClarityProc.Epic_CLARITY_UCL_DataTyping";
        public static readonly SQLProc EpicClarityUclSetCurrent = "rawEmrEpicClarityProc.Epic_CLARITY_UCL_SetCurrent";
        public static readonly SQLProc EpicHspAccountDataTyping = "rawEmrEpicClarityProc.Epic_HSP_ACCOUNT_DataTyping";
        public static readonly SQLProc EpicHspAccountSetCurrent = "rawEmrEpicClarityProc.Epic_HSP_ACCOUNT_SetCurrent";
        public static readonly SQLProc EpicHspAcctCptCodesDataTyping = "rawEmrEpicClarityProc.Epic_HSP_ACCT_CPT_CODES_DataTyping";
        public static readonly SQLProc EpicHspAcctCptCodesSetCurrent = "rawEmrEpicClarityProc.Epic_HSP_ACCT_CPT_CODES_SetCurrent";
        public static readonly SQLProc EpicHspTransactionsDataTyping = "rawEmrEpicClarityProc.Epic_HSP_TRANSACTIONS_DataTyping";
        public static readonly SQLProc EpicHspTransactionsSetCurrent = "rawEmrEpicClarityProc.Epic_HSP_TRANSACTIONS_SetCurrent";
        public static readonly SQLProc EpicPatEncDataTyping = "rawEmrEpicClarityProc.Epic_PAT_ENC_DataTyping";
        public static readonly SQLProc EpicPatEncHspDataTyping = "rawEmrEpicClarityProc.Epic_PAT_ENC_HSP_DataTyping";
        public static readonly SQLProc EpicPatEncHspSetCurrent = "rawEmrEpicClarityProc.Epic_PAT_ENC_HSP_SetCurrent";
        public static readonly SQLProc EpicPatEncSetCurrent = "rawEmrEpicClarityProc.Epic_PAT_ENC_SetCurrent";
        public static readonly SQLProc EpicZcAcctBaseclsHaDataTyping = "rawEmrEpicClarityProc.Epic_ZC_ACCT_BASECLS_HA_DataTyping";
        public static readonly SQLProc EpicZcAcctBaseclsHaSetCurrent = "rawEmrEpicClarityProc.Epic_ZC_ACCT_BASECLS_HA_SetCurrent";
        public static readonly SQLProc EpicZcAcctClassHaDataTyping = "rawEmrEpicClarityProc.Epic_ZC_ACCT_CLASS_HA_DataTyping";
        public static readonly SQLProc EpicZcAcctClassHaSetCurrent = "rawEmrEpicClarityProc.Epic_ZC_ACCT_CLASS_HA_SetCurrent";
        public static readonly SQLProc EpicZcDischDispDataTyping = "rawEmrEpicClarityProc.Epic_ZC_DISCH_DISP_DataTyping";
        public static readonly SQLProc EpicZcDischDispSetCurrent = "rawEmrEpicClarityProc.Epic_ZC_DISCH_DISP_SetCurrent";
        public static readonly SQLProc EpicZcEventSubtypeDataTyping = "rawEmrEpicClarityProc.Epic_ZC_EVENT_SUBTYPE_DataTyping";
        public static readonly SQLProc EpicZcEventSubtypeSetCurrent = "rawEmrEpicClarityProc.Epic_ZC_EVENT_SUBTYPE_SetCurrent";
        public static readonly SQLProc EpicZcEventTypeDataTyping = "rawEmrEpicClarityProc.Epic_ZC_EVENT_TYPE_DataTyping";
        public static readonly SQLProc EpicZcEventTypeSetCurrent = "rawEmrEpicClarityProc.Epic_ZC_EVENT_TYPE_SetCurrent";
        public static readonly SQLProc EpicZcMcAdmTypeDataTyping = "rawEmrEpicClarityProc.Epic_ZC_MC_ADM_TYPE_DataTyping";
        public static readonly SQLProc EpicZcMcAdmTypeSetCurrent = "rawEmrEpicClarityProc.Epic_ZC_MC_ADM_TYPE_SetCurrent";
        public static readonly SQLProc GetPatientEncounterTree = "rawEmrEpicClarityProc.GetPatientEncounterTree";
        public static readonly SQLProc GetPatientEncounterTreeAll = "rawEmrEpicClarityProc.GetPatientEncounterTreeAll";
        public static readonly SQLProc GetPatientEncounterTreeViaList = "rawEmrEpicClarityProc.GetPatientEncounterTreeViaList";
        public static readonly SQLProc GetPatientEncounterViaListV2 = "rawEmrEpicClarityProc.GetPatientEncounterViaListV2";
        public static readonly SQLProc LaborChargesPopulate = "rawEmrEpicClarityProc.Labor_Charges_Populate";
        public static readonly SQLProc LaborDepartmentIdentifiersPopulate = "rawEmrEpicClarityProc.Labor_DepartmentIdentifiers_Populate";
        public static readonly SQLProc LaborPatientEncounterPopulate = "rawEmrEpicClarityProc.Labor_PatientEncounter_Populate";
        public static readonly SQLProc LaborPatientEncounterPopulateViaTemp = "rawEmrEpicClarityProc.Labor_PatientEncounter_PopulateViaTemp";
        public static readonly SQLProc LaborPatientEncounterIdentifiersPopulate = "rawEmrEpicClarityProc.Labor_PatientEncounterIdentifiers_Populate";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
