// <auto-generated/>
#nullable enable
// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace DevKits.Data.Tests.Databases.ChiLaborProductivity;
using DevKits.Data;
using DevKits.Data.Core;


public static partial class LaborProductivity
{
    public static class Layout {
        public static readonly string Name = "layout";

        // TABLES
        public static readonly QualifiedTableName Areas = "layout.Areas";
        public static readonly QualifiedTableName DocumentPages = "layout.DocumentPages";
        public static readonly QualifiedTableName Documents = "layout.Documents";
        public static readonly QualifiedTableName FileTypes = "layout.FileTypes";
        public static readonly QualifiedTableName ModuleDocuments = "layout.ModuleDocuments";
        public static readonly QualifiedTableName ModulePages = "layout.ModulePages";
        public static readonly QualifiedTableName ModuleSectionPages = "layout.ModuleSectionPages";
        public static readonly QualifiedTableName Pages = "layout.Pages";
        public static readonly QualifiedTableName PageVisuals = "layout.PageVisuals";
        public static readonly QualifiedTableName Positions = "layout.Positions";
        public static readonly QualifiedTableName Units = "layout.Units";
    }

}
// Rev: V20240315023146 | Database: DCM_thi_productivity_impl
