namespace DevKits.Data.Core;


/// <summary>
/// Defines the attributes that can be applied to a database column.
/// These attributes specify characteristics about columns such as nullability, uniqueness, and whether the column is a primary key, among others.
/// </summary>
[Flags]
public enum ColumnAttributes
{
    /// <summary>
    /// Specifies that the column has no special attributes.
    /// </summary>
    None = 0,

    /// <summary>
    /// Indicates that the column allows NULL values.
    /// </summary>
    IsNullable = 1,

    /// <summary>
    /// Indicates that the column's value can be updated.
    /// </summary>
    IsUpdatable = 2,

    /// <summary>
    /// Marks the column as a primary key.
    /// </summary>
    IsPrimaryKey = 4,

    /// <summary>
    /// Designates the column as a unique key, ensuring that no two rows have the same value in this column.
    /// </summary>
    IsUniqueKey = 8,

    /// <summary>
    /// Indicates that the column is an auto-incrementing number, typically used for primary keys.
    /// </summary>
    IsAutoNumber = 16,

    /// <summary>
    /// Marks the column as a foreign key, linking to a primary key in another table.
    /// </summary>
    IsForeignKey = 32,

    /// <summary>
    /// Indicates that the column is indexed, which can improve search performance.
    /// </summary>
    IsIndexed = 64,

    /// <summary>
    /// Specifies that the column's value is computed and not stored physically.
    /// </summary>
    IsComputed = 128,

    /// <summary>
    /// Identifies the column as a unique identifier for a row, often used with GUIDs.
    /// </summary>
    IsRowGuidColumn = 256,

    /// <summary>
    /// Indicates that the column's value is always generated by the database, not provided by the user.
    /// </summary>
    IsGeneratedAlways = 512,

    /// <summary>
    /// Specifies that the column's value is generated by the database at the start of a row's lifetime.
    /// </summary>
    IsGeneratedAlwaysAtRowStart = 1024,

    /// <summary>
    /// Specifies that the column's value is generated by the database at the end of a row's lifetime.
    /// </summary>
    IsGeneratedAlwaysAtRowEnd = 2048,

    /// <summary>
    /// Indicates that the column stores binary large objects (BLOBs) in a file system rather than directly in the database.
    /// </summary>
    IsFileStream = 8192,

    /// <summary>
    /// Designates the column to store XML documents.
    /// </summary>
    IsXmlDocument = 16384,

    /// <summary>
    /// Marks the column as part of a column set, which allows for the storage of unstructured or semi-structured data.
    /// </summary>
    IsColumnSet = 32768,

    /// <summary>
    /// Indicates that the column is a timestamp, automatically updated whenever the row is modified.
    /// </summary>
    IsTimeStamp = 65536
}

//[Flags]
//public enum ColumnAttributes
//{
//    None = 0,
//    IsNullable = 1,
//    IsUpdatable = 2,
//    IsPrimaryKey = 4,
//    IsUniqueKey = 8,
//    IsAutoNumber = 16,
//    IsForeignKey = 32,
//    IsIndexed = 64,
//    IsComputed = 128,
//    IsRowGuidColumn = 256,
//    IsGeneratedAlways = 512,
//    IsGeneratedAlwaysAtRowStart = 1024,
//    IsGeneratedAlwaysAtRowEnd = 2048,
//    IsFileStream = 8192,
//    IsXmlDocument = 16384,
//    IsColumnSet = 32768,
//    IsTimeStamp = 65536
//}